volumes:
  pg_data:
  static:
  media:
  logs:

services:

  db:
    container_name: db
    image: postgres:17
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    env_file: .env
    build: ../backend/
    volumes:
      - static:/app/static
      - media:/app/media
      - logs:/app/logs
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    container_name: foodgram-proxy
    build: ../nginx/
    ports:
      - ${GATEWAY_PORTS_DEV}
    volumes:
      - static:/static
      - media:/app/media
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend
