volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:17
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    env_file: ../.env
    build: ../backend/
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    container_name: foodgram-proxy
    env_file: ../.env
    build: ../nginx/
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend
